---
title: "Weekly Summary Template"
author: "Author Name"
title-block-banner: true
title-block-style: default
toc: true
format: html
# format: pdf
---

---

## Tuesday, Jan 17

::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. Exploratory Data Analysis
1. The definition of clean data
1. Examples of data verbs

:::

Provide more concrete details here. You can also use footenotes[^footnote] if you like

```{R results='hide'}
#| output: false
library(dplyr)
library(purrr)
```

In Class we learned the definition of exploratory data analysis:

1.Exploratory data analysis is the process of analyzing and visualizing the data to get a better understanding of it.
1.dplyr and ggplot2 are used to facilitate it.


In class we learned about the characteristics of clean data:

1.Each case should be a different value
1.Every variable should have its own column
1.Every observation its own row
1.Every cell a unique value


We also learned about important data verbs which include:

1.select - selects a subset of columns
1.mutate - create new columns from existing ones
1.filter - selects a subset of rows


## Thursday, Jan 19



::: {.callout-important}
## TIL

Include a _very brief_ summary of what you learnt in this class here. 

Today, I learnt the following concepts in class:

1. Basics of ggthemeassist
1. The different data types
1. Factors and ways to arrange them
:::

Provide more concrete details here, e.g., 

In class we learned about ggthemeassist:

1.ggthemeassist is a feature of ggplot2 that allows you to easily alter aspects of a ggplot

We also learned about the different data types:

1.String e.g. "this is a character"
1.Integer e.g. [1,2,3]
1.Double e.g. [2.2, 3.14159, 0.9]
1.Booleans e.g. TRUE/FALSE

Finally we learned about factors:

1.Factors in R are categorical variables
1.as.factor-allows you to reorder factors
